apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: frr-k8s
    localASN: 65200
    peers:
    - name: "frr"
      peerASN: 65002
      peerAddress: 10.20.20.2
      peerConfigRef:
        name: "cilium-peer"
