apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: lab-eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: lab-eg-config
    namespace: envoy-gateway-system
